version: "3.8"

services:

  app:
    build: .
    container_name: fcms_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: fcms_database
    restart: always
    environment:
      MYSQL_DATABASE: funeral_system
      MYSQL_USER: fcms_user
      MYSQL_PASSWORD: fcms_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: